### ISSUE TITLE
Little mistake in the example

### ISSUE THREAD

**Issue by leiluspocus** [davidmpaz/rest-curlclient-php#1]
Hi,

I just wanted to tell you there were a small issue on the example: You need to instanciate a RestCurlClient not a RestClientCurl.

Thank you for this repo :)

**Comment by davidmpaz** [comment]
Hi, thanks!!

It was fixed [here](https://github.com/davidmpaz/rest-curlclient-php/pull/2). Sorry for the late reply.
cheers.
